language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.'* ]]; then easy_install --upgrade distribute; fi
  - easy_install Cython
install: python setup.py install
script: python setup.py test
