language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.'* ]]; then pip install --use-mirrors --upgrade distribute; fi
  - pip install --use-mirrors Cython
install: python setup.py install
script: python setup.py test
